"""add initial persistence schema

Revision ID: 3c6ddcf6100e
Revises:
Create Date: 2026-07-19 00:18:09.790113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3c6ddcf6100e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_sessions",
        sa.Column("task_family", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="draft", nullable=False),
        sa.Column(
            "tool_permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'completed', 'failed')",
            name="ck_evaluation_sessions_valid_status",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_sessions")),
    )
    op.create_index(
        "ix_evaluation_sessions_status_created_at",
        "evaluation_sessions",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "artifacts",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("parser_version", sa.String(length=128), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name="nonnegative_size"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["evaluation_sessions.id"],
            name=op.f("fk_artifacts_session_id_evaluation_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("object_key", name=op.f("uq_artifacts_object_key")),
    )
    op.create_index(
        "ix_artifacts_session_created_at", "artifacts", ["session_id", "created_at"], unique=False
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("frozen_request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("environment_hash", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'partial', 'failed', 'cancelled')",
            name="ck_evaluation_runs_valid_status",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["evaluation_sessions.id"],
            name=op.f("fk_evaluation_runs_session_id_evaluation_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_index(
        "ix_evaluation_runs_session_status",
        "evaluation_runs",
        ["session_id", "status"],
        unique=False,
    )
    op.create_table(
        "model_runs",
        sa.Column("evaluation_run_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("model_revision", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "tool_trace",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed', 'timeout')",
            name="ck_model_runs_valid_status",
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0", name="nonnegative_input_tokens"
        ),
        sa.CheckConstraint("latency_ms IS NULL OR latency_ms >= 0", name="nonnegative_latency"),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0", name="nonnegative_output_tokens"
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"],
            ["evaluation_runs.id"],
            name=op.f("fk_model_runs_evaluation_run_id_evaluation_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    op.create_index(
        "ix_model_runs_evaluation_run_status",
        "model_runs",
        ["evaluation_run_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_runs_evaluation_run_status", table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_index("ix_evaluation_runs_session_status", table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index("ix_artifacts_session_created_at", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index("ix_evaluation_sessions_status_created_at", table_name="evaluation_sessions")
    op.drop_table("evaluation_sessions")
    # ### end Alembic commands ###
